import { ContractType } from '@/types';

const DISCLAIMER = "\n\n---\n\nDISCLAIMER: This document is generated by an AI system and does not constitute legal advice. Seek independent legal advice before use.";

export const generateContractFromAnswers = (
  contractType: ContractType,
  answers: Record<string, any>
): string => {
  const {
    party1Name = '[PARTY 1 NAME]',
    party1Address = '[PARTY 1 ADDRESS]',
    party2Name = '[PARTY 2 NAME]',
    party2Address = '[PARTY 2 ADDRESS]',
    startDate = '[START DATE]',
    term = '[TERM]',
    fees = '[FEES]',
    jurisdiction = 'Australia',
  } = answers;

  let contract = `${contractType.name.toUpperCase()}\n\n`;
  contract += `This Agreement is entered into on ${startDate} between:\n\n`;
  contract += `Party 1: ${party1Name}, located at ${party1Address} ("Party A")\n\n`;
  contract += `Party 2: ${party2Name}, located at ${party2Address} ("Party B")\n\n`;
  contract += `BACKGROUND\n\n`;
  contract += `The parties wish to enter into a formal agreement governing their relationship.\n\n`;
  contract += `AGREED TERMS\n\n`;
  contract += `1. DEFINITIONS\n\n`;
  contract += `In this Agreement, unless the context otherwise requires, the following terms have the meanings set out below.\n\n`;
  contract += `2. SCOPE OF SERVICES\n\n`;
  contract += `Party A agrees to provide services as mutually agreed by the parties from time to time.\n\n`;
  contract += `3. TERM\n\n`;
  contract += `This Agreement shall commence on ${startDate} and continue for a period of ${term}, unless terminated earlier in accordance with this Agreement.\n\n`;
  contract += `4. FEES AND PAYMENT\n\n`;
  contract += `Party B agrees to pay Party A fees in the amount of ${fees} as consideration for the services provided.\n\n`;
  contract += `5. CONFIDENTIALITY\n\n`;
  contract += `Each party agrees to maintain the confidentiality of all information disclosed by the other party during the term of this Agreement.\n\n`;
  contract += `6. INTELLECTUAL PROPERTY\n\n`;
  contract += `All intellectual property created in the course of this Agreement shall be owned as agreed by the parties.\n\n`;
  contract += `7. WARRANTIES AND REPRESENTATIONS\n\n`;
  contract += `Each party warrants that it has the authority to enter into this Agreement and perform its obligations.\n\n`;
  contract += `8. INDEMNITY\n\n`;
  contract += `Each party agrees to indemnify the other against any losses arising from breach of this Agreement.\n\n`;
  contract += `9. LIMITATION OF LIABILITY\n\n`;
  contract += `Neither party shall be liable for indirect, consequential, or punitive damages.\n\n`;
  contract += `10. TERMINATION\n\n`;
  contract += `Either party may terminate this Agreement by providing written notice as specified in this Agreement.\n\n`;
  contract += `11. DISPUTE RESOLUTION\n\n`;
  contract += `Any disputes arising from this Agreement shall be resolved through mediation, and if unsuccessful, through arbitration.\n\n`;
  contract += `12. GOVERNING LAW\n\n`;
  contract += `This Agreement shall be governed by and construed in accordance with the laws of ${jurisdiction}.\n\n`;
  contract += `13. GENERAL\n\n`;
  contract += `This Agreement constitutes the entire agreement between the parties and supersedes all prior negotiations and agreements.\n\n`;
  contract += `SIGNATURES\n\n`;
  contract += `Party A: _________________________  Date: __________\n\n`;
  contract += `Party B: _________________________  Date: __________\n\n`;
  contract += DISCLAIMER;

  return contract;
};

export const getNextQuestion = (
  contractType: ContractType,
  currentAnswers: Record<string, any>,
  questionIndex: number
): string | null => {
  const questions = [
    "What is the full legal name of the first party?",
    "What is the address of the first party?",
    "What is the full legal name of the second party?",
    "What is the address of the second party?",
    "What is the start date of this agreement?",
    "What is the term or duration of this agreement?",
    "What are the fees or compensation involved?",
    "What jurisdiction or governing law applies?",
  ];

  if (questionIndex >= questions.length) {
    return null;
  }

  return questions[questionIndex];
};
